import {
  StyleSheet,
  Text,
  View,
  Button,
  TextInput,
  FlatList,
  Pressable,
  Modal,
  Image,
} from "react-native";
import { useState } from "react";

export default function App() {
  const [enteredMovieText, setEnteredMovieText] = useState("");
  const [movieList, setMovieList] = useState([]);
  const [modalIsVisible, setModalIsVisible] = useState(false);

  function modalIsVisibleHandler() {
    setModalIsVisible(true);
  }
  function modalIsNotVisible() {
    setModalIsVisible(false);
  }

  function movieInputHandler(enteredText) {
    setEnteredMovieText(enteredText);
  }

  function addMovieHandler() {
    setMovieList((currentMovies) => [
      ...currentMovies,
      {
        text: enteredMovieText,
        // key: Math.random().toString(),
        id: Math.random().toString(),
      },
    ]);
  }

  function deleteMovieHandler(id) {
    setMovieList((currentMovies) => {
      return currentMovies.filter((movie) => movie.id !== id);
    });
  }

  return (
    <View style={styles.appContainer}>
      <Button
        title="Tap to Create List"
        color={"red"}
        onPress={modalIsVisibleHandler}
      />

      <Modal visible={modalIsVisible} animationType="slide">
        <View style={styles.inputContainer}>
          <Image
            style={styles.imageStyle}
            source={require("./assets/images/ironman2.png")}
          />
          <TextInput
            style={styles.textInput}
            placeholder="Enter your favourite movie name"
            onChangeText={movieInputHandler}
          />
          <View style={styles.buttonContainer}>
            <View style={styles.twoButtons}>
              <Button title="Back" color={"red"} onPress={modalIsNotVisible} />
            </View>
            <View style={styles.twoButtons}>
              <Button
                title="Add movie"
                onPress={addMovieHandler}
                color={"blue"}
              />
            </View>
          </View>
        </View>
      </Modal>

      {/* checking whether modal is visible or not */}
      {modalIsVisible}
      <View style={styles.movieListContainer}>
        <FlatList
          data={movieList}
          // itemData is an object generated by FlatList internally
          // it is an object that does not contain only our values but also some meta data.
          renderItem={(itemData) => {
            return (
              <View style={styles.movieNames}>
                <Pressable
                  android_ripple={{ color: "#dddddd" }}
                  onPress={deleteMovieHandler.bind(self, itemData.item.id)}
                >
                  <Text style={styles.singleMovieName}>
                    {itemData.item.text}
                  </Text>
                </Pressable>
              </View>
            );
          }}
          // item, index : these two items are provided by the FlatList automatically
          keyExtractor={(item, index) => {
            return item.id;
          }}
        ></FlatList>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  appContainer: {
    flex: 1,
    marginTop: 50,
    marginHorizontal: 8,
  },

  inputContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "black",
    // backgroundColor: "aliceblue",
  },

  buttonContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  imageStyle: {
    resizeMode: "contain",
    height: 200,
    width: 200,
    margin: 25,
  },

  twoButtons: {
    margin: 8,
    width: "40%",
  },

  textInput: {
    borderWidth: 1,
    borderColor: "blue",
    width: "85%",
    paddingLeft: 6,
  },

  movieListContainer: {
    margin: 8,
    flex: 5,
  },

  movieNames: {
    margin: 10,
    borderRadius: 5,
    backgroundColor: "blue",
  },

  singleMovieName: {
    color: "white",
    padding: 8,
  },
});
